version: '3'
services:
  lwr:
    image: lwr_dev
    hostname: ${APP_HOSTNAME:-lwr}
    build:
      context: .
      target: development
      args:
        WWWGROUP: '${WWWGROUP}'
    ports:
      - ${APP_PORT:-80}:80
      - ${WPDS_PORT:-3000}:${WPDS_PORT:-3000}
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - ./:/var/www/html
      - ${NPM_CACHE:-/var/www/html/npm/cache}:/root/.npm
    networks:
      - sail
      
  lwr_mobile:
    image: lwr_dev
    build:
      context: .
      target: development
      args:
        WWWGROUP: '${WWWGROUP}'
    hostname: ${APP_HOSTNAME:-lwr}
    ports:
      - ${APP_MOBILE_PORT:-8080}:80
      - ${WPDS_MOBILE_PORT:-3001}:${WPDS_MOBILE_PORT:-3001}
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      APP_IS_MOBILE: 'true'
    volumes:
      - ./:/var/www/html
      - ${NPM_CACHE:-/var/www/html/npm/cache}:/root/.npm
    depends_on:
      - lwr
    networks:
      - sail

  mailhog:
    image: 'mailhog/mailhog:latest'
    hostname: ${FORWARD_MAILHOG_HOSTNAME:-mailhog}
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail

networks:
  sail:
    external: true
    name: lwr_network

volumes:
  sailmeilisearch:
    driver: local
